package main

import "strings"

// normalizeHandoffLegacy removes presentation wrappers and retired feature
// fields from a previously exported handoff before the v1 formatter appends
// the current appendix.  A v0.9.x handoff is otherwise useful migration
// input, so ordinary/unknown key-value lines are deliberately retained.
func normalizeHandoffLegacy(legacy string, regenerated map[string]struct{}) string {
	normalized := strings.ReplaceAll(legacy, "\r\n", "\n")
	changed := normalized != legacy
	lines := strings.Split(normalized, "\n")
	kept := make([]string, 0, len(lines))
	for _, raw := range lines {
		line := strings.TrimSuffix(raw, "\r")
		trimmed := strings.TrimSpace(line)
		if isHandoffPresentationLine(trimmed) {
			changed = true
			continue
		}
		if key, _, ok := strings.Cut(trimmed, "="); ok {
			key = strings.TrimSpace(key)
			if _, drop := regenerated[key]; drop || retiredHandoffField(key) {
				changed = true
				continue
			}
		} else if retiredHandoffRow(trimmed) {
			changed = true
			continue
		}
		kept = append(kept, line)
	}
	if !changed {
		// Preserve the byte sequence for ordinary legacy handoffs.  This keeps
		// older consumers' append-only expectation while still canonicalizing
		// payloads that actually contain stale wrappers or retired fields.
		return legacy
	}
	return strings.TrimSpace(strings.Join(kept, "\n"))
}

func isHandoffPresentationLine(line string) bool {
	if line == "" {
		return false
	}
	upper := strings.ToUpper(line)
	// Marker pairs can be nested when an operator pastes a previously copied
	// handoff back into a state file.  Keep the payload, but never render the
	// marker text as part of the visible v1 form.
	if strings.HasPrefix(line, "__") && strings.HasSuffix(line, "__") && strings.Contains(upper, "HANDOFF") {
		return true
	}
	if strings.Trim(line, "=") == "" && len(line) >= 8 {
		return true
	}
	if !strings.HasPrefix(line, "=") {
		return false
	}
	for _, phrase := range []string{
		"COMPLETE HANDOFF",
		"REQUIRED LOGIN CREDENTIALS",
		"REAL CREDENTIAL HANDOFF",
		"CURRENT 3X-UI HANDOFF",
		"REAL GENERATED REALITY",
		"MANDATORY DRIVE",
		"ORDINARY DRIVE",
		"PRIVATE DRIVE",
	} {
		if strings.Contains(upper, phrase) {
			return true
		}
	}
	return false
}

func retiredHandoffRow(line string) bool {
	upper := strings.ToUpper(line)
	return strings.HasPrefix(upper, "DEVICE\t") ||
		strings.HasPrefix(upper, "CONTROLLER\t")
}

func retiredHandoffField(key string) bool {
	upper := strings.ToUpper(strings.TrimSpace(key))
	switch upper {
	case "CURRENT_DEVICE_ID", "LOCAL_DEVICE_ID", "DEVICE_ID", "DEVICE_ROLE",
		"DEVICE_PUBLIC_KEY", "ENCRYPTION_PUBLIC_KEY", "PRIVATE_IDENTITY_STORAGE",
		"DEVICE_ADMISSION", "INVITE_POLICY", "ACTIVE_CONTROLLERS", "ACTIVE_DEVICES",
		"PER_DEVICE_VLESS", "CDN_MTLS_DEVICE", "WIREGUARD_DEVICE_LOCK",
		"OWNER_DEVICE_ID", "FENCING_TOKEN", "CURRENT_STAGE", "LAST_HEARTBEAT",
		"TNA_VERSION":
		return true
	}
	for _, prefix := range []string{
		"PRIVATE_DRIVE_",
		"DRIVE_",
		"MANDATORY_DRIVE_",
		"LOCAL_ADMIN_",
		"TNA_LOCAL_ADMIN_",
		"DEVICE_",
		"TNA_DEVICE_",
		"PNA_DEVICE_",
		"CONTROLLER_",
		"TNA_CONTROLLER_",
		"PNA_CONTROLLER_",
		"NODE_OPERATION_",
		"LEASE_",
		"INVITE_",
		"INVITATION_",
	} {
		if strings.HasPrefix(upper, prefix) {
			return true
		}
	}
	return false
}

func handoffRegeneratedKeys(fields map[string]string, formComplete bool) map[string]struct{} {
	keys := make(map[string]struct{}, len(fields)+8)
	for key := range fields {
		keys[key] = struct{}{}
	}
	// A legacy handoff may expose the same CDN URI under either the old
	// XHTTP_* aliases or the newer CDN_XHTTP_* names.  Once one canonical link
	// is being regenerated, remove every alias from the preserved prefix; this
	// prevents an old TNA-* fragment from remaining visible beside the PNA v1
	// value.  The appendix itself contains only the keys supplied by the caller.
	cdnLinkPresent := false
	for key := range fields {
		if _, ok := completeHandoffCDNLinkKeys[key]; ok {
			cdnLinkPresent = true
			break
		}
	}
	if cdnLinkPresent {
		for key := range completeHandoffCDNLinkKeys {
			keys[key] = struct{}{}
		}
	}
	if formComplete {
		// These aliases are generated by the desktop/Android presentation
		// layer, not by the remote handoff file.  Drop stale copies so the
		// form shows one current credential block.  The four VPS_LOGIN_ /
		// PANEL_USERNAME aliases are the *source* vocabulary used by the
		// v0.9.x runbook; leaving them in the rendered form makes an in-place
		// upgrade look as if two (possibly different) passwords are current.
		for _, key := range []string{
			"VPS_ACCOUNT", "VPS_PASSWORD", "PANEL_ACCOUNT", "PANEL_PASSWORD", "PANEL_LOCAL_URL",
			"FORM_VPS_ACCOUNT", "FORM_VPS_PASSWORD", "FORM_PANEL_ACCOUNT", "FORM_PANEL_PASSWORD",
			"VPS_LOGIN_USER", "VPS_LOGIN_PASSWORD", "PANEL_USERNAME",
		} {
			keys[key] = struct{}{}
		}
	}
	return keys
}
